# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('music_genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'music_genre',
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('music_track_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('rates', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'music_track',
            },
        ),
        migrations.CreateModel(
            name='TrackGenre',
            fields=[
                ('track_genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('music_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.MusicGenre')),
                ('music_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.MusicTrack')),
            ],
            options={
                'db_table': 'track_genre',
            },
        ),
    ]
