# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20170425_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicgenre',
            name='music_genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='music_track_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackgenre',
            name='track_genre_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
